#!/usr/bin/env python
#
#Test program for MathSpeak text-to-speech translation
#See the file COPYING for more details.
#Copyright 2012 World Light Information Limited and Hong Kong Blind Union.


from optparse import OptionParser
#from mathspeak.en import MathSpeak


def main():
	# Parse command line
	parser=OptionParser(usage="usage: %prog [options] file")
	parser.add_option(
		"-v", "--verbose",
		action="store_const", dest="verbosity", const="verbose",
		help="Set verbosity to 'verbose'")
	parser.add_option(
		"-b", "--brief",
		action="store_const", dest="verbosity", const="brief",
		help="Set verbosity to 'brief'")
	parser.add_option(
		"-s", "--superbrief",
		action="store_const", dest="verbosity", const="superbrief",
		help="Set verbosity to 'superbrief'")
	parser.add_option(
		"-l", "--locale", dest="locale", default="en",
		help="Specify target locale")
	(options,files)=parser.parse_args()

	# Validate command line options
	if len(files) < 1:
		parser.error("no input file")
	if len(files) > 1:
		parser.error("too many input files")

	# Load target locale module
	try:
		modules=__import__("mathspeak."+options.locale,
				globals(),locals(),["mathspeak"])
	except:
		parser.error("unknown locale")
	MathSpeak=modules.MathSpeak

	# Perform translation now
	try:
		math=open(files[0],"rb").read()
	except:
		parser.error("cannot open input file")
	text=MathSpeak().translate(math,options.verbosity)
	if text=="":
		math="<mathspeak>"+math+"</mathspeak>"
		text=MathSpeak().translate(math,options.verbosity)
	print text.encode("utf-8")


if __name__=="__main__":
	main()


# vim: set tabstop=4 shiftwidth=4:
