#!/usr/bin/env python
#
#Test program for MathSpeak text-to-speech translation
#See the file COPYING for more details.
#Copyright 2012-2013 World Light Information Limited and Hong Kong Blind Union.


from optparse import OptionParser
import sys


def main():
	# Parse command line
	parser=OptionParser(usage=u"usage: %prog [options] file")
	parser.add_option(
		"-v", u"--verbose",
		action=u"store_const", dest=u"verbosity", const=u"verbose",
		help=u"Set verbosity to 'verbose'")
	parser.add_option(
		"-b", u"--brief",
		action=u"store_const", dest=u"verbosity", const=u"brief",
		help=u"Set verbosity to 'brief'")
	parser.add_option(
		"-s", u"--superbrief",
		action=u"store_const", dest=u"verbosity", const=u"superbrief",
		help=u"Set verbosity to 'superbrief'")
	parser.add_option(
		"-l", u"--locale", dest=u"locale", default=u"en",
		help=u"Specify target locale")
	(options,files)=parser.parse_args()

	# Validate command line options
	if len(files) < 1:
		parser.error(u"no input file")
	if len(files) > 1:
		parser.error(u"too many input files")

	# Load target locale module
	try:
		modules=__import__(u"mathspeak."+options.locale,
				globals(),locals(),[u"mathspeak"])
	except:
		parser.error(u"unknown locale")
	MathSpeak=modules.MathSpeak

	# Perform translation now
	try:
		math=open(files[0],u"rb").read()
	except:
		parser.error(u"cannot open input file")
	text=MathSpeak().translate(math,options.verbosity)
	if text==u"":
		math=u"<mathspeak>"+math+u"</mathspeak>"
		text=MathSpeak().translate(math,options.verbosity)
	if sys.version_info[0]<3:  text=text.encode(u"utf-8")
	print(text)


if __name__==u"__main__":
	main()


# vim: set tabstop=4 shiftwidth=4:
